version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '02:00'
  open-pull-requests-limit: 5
  reviewers:
    - arpadgabor
  assignees:
    - arpadgabor
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
