name: Build and deploy
on:
  push:
    branches:
      - master

env:
  BASE_TAG: actm/ac-admissions

jobs:
  build-and-deploy:
    name: Build, deploy to Netlify and upload docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install deps
        run: rm -rf node_modules && npm install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Generate static build
        run: npm run generate
        env:
          NODE_ENV: production
          URL: https://admitere-next.netlify.app

      - name: Build image
        run: |
          docker build \
          --tag $BASE_TAG:latest \
          --tag $BASE_TAG:$(echo $GITHUB_SHA | head -c7) \
          .

      - name: Push image to Docker Hub
        run: |
          docker push $BASE_TAG:latest
          docker push $BASE_TAG:$(echo $GITHUB_SHA | head -c7)

      - name: Deploy to Netlify
        run: |
          npm i -g netlify-cli@11
          netlify deploy --auth $TOKEN --site $SITE --dir dist --prod --message "${{ github.event.commits[0].message }}"
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
          SITE: ${{ secrets.NETLIFY_SITE_ID }}
          TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
