name: Build and deploy
on: push

jobs:
  build-and-deploy:
    name: Build, deploy to Netlify and upload docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: bahmutov/npm-install@v1
      - run: npm t

      - name: Install deps
        run: npm ci

      - name: Generate static build
        run: npm run generate

      - name: Deploy to Netlify
        run: |
          npm i -g netlify-cli
          netlify --auth $TOKEN --site $SITE deploy --dir dist --prod
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
          SITE: ${{ secrets.NETLIFY_SITE_ID }}
          TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Publish to DockerHub
        run: |
          docker login -u $USER --password-stdin $PASS
          docker build . -t $TAG
          docker push $TAG
        env:
          TAG: actm/ac-admissions:latest
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASS: ${{ secrets.DOCKER_PASSWORD }}
